In [4]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

data = pd.read_csv('./Data/train.csv')

In [5]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data) # shuffle before splitting into dev and training sets

data_dev = data[0:1000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[1000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [6]:
Y_train

array([6, 2, 3, ..., 1, 1, 8])

In [7]:
X_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [34]:
def init_params():
    W1 = np.random.randn(10, 784) * 0.5
    b1 = np.random.rand(10, 1) * 0.5
    W2 = np.random.randn(10, 10) * 0.5
    b2 = np.random.rand(10, 1) * 0.5
    return W1, b1, W2, b2

def ReLu(z):
    return np.maximum(0, z)

def softmax(z):
    return np.exp(z) / sum(np.exp(z))

def ReLU_deriv(Z):
    return Z > 0

def forward_prop(W1, b1, W2, b2, X):
    Z1 = np.dot(W1, X) + b1
    A1 = ReLu(Z1)
    Z2 = np.dot(W2, A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def backwards_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = (1/m) * np.dot(dZ2, A1.T)
    dB2 = (1/m) * np.sum(dZ2)
    
    dZ1 = np.dot(W2.T, dZ2) * ReLU_deriv(Z1)
    dW1 = (1/m) * np.dot(dZ1, X.T)
    dB1 = (1/m) * np.sum(dZ1, axis = 1, keepdims = True)
    
    return dW2, dB2, dW1, dB1

def update_params(W1, b1, W2, b2, dW2, db2, dW1, db1, learning_rate):
    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2
    return W1, b1, W2, b2

In [35]:
def get_preds(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

In [36]:
def gradient_descent(X, Y, learning_rate, epochs):
    W1, b1, W2, b2 = init_params()
    
    for i in range(epochs):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW2, dB2, dW1, dB1 = backwards_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW2, dB2, dW1, dB1, learning_rate)
        if i % 10 == 0:
            print("Iteration: ", i)
            predictions = get_preds(A2)
            print(get_accuracy(predictions, Y))
    return W1, b2, W2, b2

In [37]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 0.10, 500)

Iteration:  0
[1 1 1 ... 1 1 1] [6 2 3 ... 1 1 8]
0.12851219512195122
Iteration:  10
[2 1 0 ... 6 9 6] [6 2 3 ... 1 1 8]
0.19651219512195123
Iteration:  20
[6 6 0 ... 3 9 2] [6 2 3 ... 1 1 8]
0.2652926829268293
Iteration:  30
[6 6 0 ... 8 9 2] [6 2 3 ... 1 1 8]
0.3252926829268293
Iteration:  40
[6 2 0 ... 8 3 2] [6 2 3 ... 1 1 8]
0.3580243902439024
Iteration:  50
[6 2 0 ... 8 3 2] [6 2 3 ... 1 1 8]
0.3841951219512195
Iteration:  60
[6 2 0 ... 8 3 2] [6 2 3 ... 1 1 8]
0.410390243902439
Iteration:  70
[6 2 0 ... 8 3 2] [6 2 3 ... 1 1 8]
0.4344390243902439
Iteration:  80
[6 6 0 ... 8 8 2] [6 2 3 ... 1 1 8]
0.4574390243902439
Iteration:  90
[6 6 0 ... 8 8 2] [6 2 3 ... 1 1 8]
0.4785121951219512
Iteration:  100
[6 6 0 ... 8 8 2] [6 2 3 ... 1 1 8]
0.49970731707317073
Iteration:  110
[6 6 0 ... 8 8 2] [6 2 3 ... 1 1 8]
0.5197073170731707
Iteration:  120
[6 6 0 ... 1 8 6] [6 2 3 ... 1 1 8]
0.5402926829268293
Iteration:  130
[6 6 0 ... 1 8 6] [6 2 3 ... 1 1 8]
0.5573414634146342
Iteration:  140